test_query_exe = executable('test_query',
                            [
                              'test_utils.cpp',
                              'test_query.cpp',
                            ],
                            dependencies: libmado_dep)

test_entry_exe = executable('test_entry',
                            [
                              'test_utils.cpp',
                              'test_entry.cpp',
                            ],
                            dependencies: libmado_dep)
